name: saturn
channels:
- https://conda.saturncloud.io/pkgs
- nvidia
- rapidsai
- pytorch
- numba
- defaults
- conda-forge
- saturncloud
dependencies:
- blas=*=mkl
- python=3.7
- numpy
- pandas
- ipywidgets
- matplotlib
- dask=2.20.0
- distributed=2.20.0
- dask-saturn=0.0.4
- xgboost
- dask-xgboost
- dask-ml
- rapids=0.14.1=cuda10.1_py37_0
- numba=0.49.1
- llvmlite=0.32.1
- snowflake-connector-python
- snowflake-sqlalchemy
- azure-storage-blob=2.1.0
- scikit-learn
- scipy
- bokeh
- h5py
- ipykernel
- graphviz
- s3fs
- dash
- dash-bootstrap-components
- dash-core-components
- dash-daq
- dash-html-components
- dash-renderer
- dash-table
- pip
- nltk
- gensim
- wordcloud
- cvxpy
- pyarrow
- fastparquet
- geopandas
- pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
- torchvision=0.5.0=py37_cu101
- tensorboard=2.1.0
- tensorflow=2.1.0=gpu_py37h7a4bb67_0
- tensorflow-base=2.1.0=gpu_py37h6c5654b_0
- tensorflow-estimator=2.1.0
- prefect
- voila